apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: cheeky77/cnad/calculator:v3
        ports:
        - containerPort: 3000