version: "3.9"

services:
  calculator:
    container_name: calculator
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - PORT=3000
    networks:
      my-network:
        ipv4_address: 172.28.0.2
    restart: "always"
  jokes:
    container_name: jokes
    build:
      context: ./jokes
      dockerfile: Dockerfile
    ports:
      - "81:3001"
    environment:
      - PORT=3001
    networks:
      my-network:
        ipv4_address: 172.28.0.3
    restart: "always"

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1