apiVersion: v1
kind: Service
metadata:
  name: mongo-ui-svc
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 31000
  selector:
    app: mongo
  type: NodePort