apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ui
  labels:
    app: mongo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ui
  template:
    metadata:
      labels:
        app: mongo-ui
    spec:
      containers:
        - name: mongo-ui
          image: cheeky77/mongo-ui-image:v1
          env:
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          